# -*- coding: utf-8 -*-
"""OasisTask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6jsAkLBqWr0EMUloC6q21_HleO2DPkJ

# Unemployment Analysis in India using Python

This project analyzes unemployment trends in India using a dataset that
contains unemployment rates, employment numbers, and labour participation rates.

The aim is to explore patterns in unemployment and understand how the
COVID-19 pandemic affected unemployment rates across different states.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

df.head()

print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns)

df.info()

df.columns = df.columns.str.strip()

df = df.rename(columns={
    'Estimated Unemployment Rate (%)': 'Unemployment_Rate',
    'Estimated Employed': 'Employed',
    'Estimated Labour Participation Rate (%)': 'Labour_Participation_Rate'
})

df.isnull().sum()

df = df.dropna()

df['Date'] = pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

df.describe()

plt.figure(figsize=(8,5))
sns.histplot(df['Unemployment_Rate'], bins=20, kde=True)

plt.title("Distribution of Unemployment Rate")
plt.xlabel("Unemployment Rate (%)")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(12,6))

sns.barplot(x='Region', y='Unemployment_Rate', data=df)

plt.xticks(rotation=90)
plt.title("Unemployment Rate by Region")

plt.show()

plt.figure(figsize=(10,6))

sns.lineplot(x='Date', y='Unemployment_Rate', data=df)

plt.title("Unemployment Rate Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")

plt.show()

covid_data = df[df['Year'] == 2020]

plt.figure(figsize=(10,6))

sns.lineplot(x='Month', y='Unemployment_Rate', data=covid_data)

plt.title("Unemployment Trend During COVID-19 (2020)")
plt.xlabel("Month")
plt.ylabel("Unemployment Rate (%)")

plt.show()

state_unemployment = df.groupby('Region')['Unemployment_Rate'].mean().sort_values(ascending=False)

plt.figure(figsize=(12,6))

state_unemployment.plot(kind='bar')

plt.title("Average Unemployment Rate by State")
plt.ylabel("Unemployment Rate (%)")

plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='Labour_Participation_Rate',
    y='Unemployment_Rate',
    data=df
)

plt.title("Labour Participation vs Unemployment Rate")

plt.show()

plt.figure(figsize=(6,4))

numeric_df = df.select_dtypes(include=['number'])

sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Between Variables")

plt.show()

"""## Conclusion

In this project, unemployment trends in India were analyzed using Python.
Different visualizations were used to understand how unemployment varies
across states and over time.

The analysis also highlights the impact of the COVID-19 pandemic on
unemployment rates.

Such analysis can help policymakers understand labour market trends
and design better employment strategies.
"""